app1/urls.py
from django.urls import path

from app1 import views

app_name = 'app1'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

artists/urls.py
from django.urls import path

from artists import views

app_name = 'artists'
urlpatterns = [
    path('', views.list, name='list'),
    path('<str:artist_slug>/', views.detail, name='detail'),
]

homepage/urls.py
from django.urls import path

from homepage import views

app_name = 'homepage'
urlpatterns = [
    path('', views.homepage, name='homepage'),
]

musicpal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/', include('todos.urls')),

    path('app1/', include('app1.urls')),
    path('', include('homepage.urls')),
    path('artists', include('artists.urls')),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
]

app1/models.py
from datetime import timezone, datetime

from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

artists/models.py
from django.db import models
from django.db.models import Q


class Artist(models.Model):
    name = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    website = models.URLField(null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.question_text

    def all_songs(self):
        from music.models import Song
        return Song.objects.filter(Q(artist=self) | Q(featured_artists__in=[self]))

    def songs(self):
        from music.models import Song
        return Song.objects.filter(artist=self)

    def featured_songs(self):
        from music.models import Song
        return Song.objects.filter(featured_artists__in=[self])

    def albums(self):
        from music.models import Album
        return Album.objects.filter(artist=self)

music/models.py
from django.db import models

from artists.models import Artist


class Album(models.Model):
    title = models.CharField(max_length=150)
    release_date = models.DateField()
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    album_art = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.question_text

    def songs(self):
        return Song.objects.filter(album=self)


class Song(models.Model):
    title = models.CharField(max_length=150)
    release_date = models.DateField()
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    length = models.TimeField()
    featured_artists = models.ManyToManyField(Artist, blank=True, related_name='featured_artists')

app1/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone

from django.shortcuts import get_object_or_404, render

from django.shortcuts import render
from django.urls import reverse

from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'app1/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'app1/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'app1/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'app1/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('app1:results', args=(question.id,)))

artists/views.py
from django.shortcuts import render


def detail(request):
    context = {}
    return render(request, 'artists/detail.html', context)


def list(request):
    context = {}
    return render(request, 'artists/list.html', context)

homepage/views.py
import billboard
from django.shortcuts import render


def homepage(request):
    hot_100 = billboard.ChartData('hot-100')
    context = {
        'hot_100': hot_100
    }
    return render(request, 'homepage/homepage.html', context)

app1/templates/app1/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'app1:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

app1/templates/app1/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'app1:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

app1/templates/app1/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'app1:detail' question.id %}">Vote again?</a>

base/templates/base/base.html
{# HTML5 declaration #}
<!DOCTYPE html>
<html>
    {# Make modifiable head elements #}
    <head>
        <title>{% block title %}Home {% endblock title %} | Music Pal</title>
        {% block head_favicon %}
            <link rel="icon" type="image/png"
                  href="{{ STATIC_URL }}images/favicon.ico">
        {% endblock head_favicon %}
        {% block head_meta %}
            {% block head_meta_charset %}
                <meta http-equiv="Content-Type"
                      content="text/html; charset=utf-8" />
            {% endblock head_meta_charset %}
            {% block head_meta_contentlanguage %}
                <meta http-equiv="Content-Language" value="en-US" />
            {% endblock head_meta_contentlanguage %}
            {% block head_meta_viewport %}
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0">
            {% endblock head_meta_viewport %}
        {% endblock head_meta %}
        {% block head_css %}
            {% block head_css_site %}
                <link href="{{ STATIC_URL }}css/bootstrap.min.css"
                      rel="stylesheet" media="screen">
                <link href="{{ STATIC_URL }}css/app.css"
                      rel="stylesheet" media="screen">
            {% endblock head_css_site %}
            {% block head_css_section %}{% endblock head_css_section %}
            {% block head_css_page %}{% endblock head_css_page %}
        {% endblock head_css %}
    </head>
    <body>
        {# Navigation Menu #}
        <header>
        </header>
        {# Body #}
        <div id="site-wrapper">
            {% block content %}{% endblock content %}
        </div>
        {# The Footer #}
        <div class="footer">
            <div class="container">
            </div>
        </div>
    </body>
    {# Set of blocks that can be used to display JavaScript files #}
    {% block footer_javascript %}
        {% block footer_javascript_site %}
            <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
            <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
            <script src="{{ STATIC_URL }}js/app.js"></script>
        {% endblock footer_javascript_site %}
        {% block footer_javascript_section %}{% endblock footer_javascript_section %}
        {% block footer_javascript_page %}{% endblock footer_javascript_page %}
    {% endblock footer_javascript %}
</html>

homepage/templates/homepage/homepage.html
{% extends 'base/base.html' %}
{% block content %}
    {% for song in hot_100.entries %}
        <div>
             <img src="{{ song.image }}"/>
             <span>
                {{ song.title }}
             </span>
             <span>
                {{ song.artist }}
             </span>
             <span>
                {{ song.rank }}
             </span>
        </div>
    {% endfor %}
{% endblock content %}